cerci/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.http import HttpResponse


urlpatterns = patterns(
    '',
    url(r'', include('cerci_frontend.urls')),
    # url(r'^cerci/', include('cerci.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^newsletters/', include('cerci_newsletters.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include('cerci_admin.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^arama/', include('haystack.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

urlpatterns += staticfiles_urlpatterns()

if settings.ENVIRONMENT == 'prod':
    urlpatterns += url(
        r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-agent: *\nAllow: /\nDisallow: /admin", content_type="text/plain")
    ),
else:
    urlpatterns += url(
        r'^robots\.txt$',
        lambda r: HttpResponse(
            "User-agent: *\nDisallow: /", content_type="text/plain")),

cerci_issue/models.py
from django.db import models
from datetime import datetime
from django.utils.translation import ugettext as _
from django.template.defaultfilters import slugify
from django.utils.timezone import now

from cerci_content.models import IssueContent, Author
from utils.cache import destroy_cache


def get_unused_contents():
    return IssueContent.objects.filter(issue=None)


class Issue(models.Model):
    number = models.IntegerField(unique=True, verbose_name=_('Number'))
    subject = models.CharField(max_length=255, verbose_name=_('Issue Subject'))
    slug = models.SlugField(
        max_length=100,
        unique=True,
        verbose_name=_('Slug'))
    editorial_title = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_('Editorial Title'))
    editorial = models.TextField(blank=True, verbose_name=_('Editorial'))
    copyright_page = models.TextField(verbose_name=_('Copyright Page'))
    cover = models.ImageField(
        upload_to="images/issue/",
        verbose_name=_('Cover'))
    cover_video = models.FileField(
        null=True, blank=True,
        upload_to="videos/issue/",
        verbose_name=_('Cover Video')
    )
    cover_design = models.ManyToManyField(
        Author, verbose_name=_('Cover Design'), null=True)
    contents = models.ManyToManyField(
        IssueContent, through="Issue2Content",
        limit_choices_to={"issue": "self"},
        verbose_name=_('Contents'))
    is_published = models.BooleanField(
        blank=True, default=False,
        verbose_name=_('Is Published'))
    published_at = models.DateField(
        null=True, blank=True, verbose_name=_('Published At'))
    created_at = models.DateTimeField(
        default=now(), verbose_name=_('Created At'))
    updated_at = models.DateTimeField(verbose_name=_('Updated At'))

    class Meta:
        verbose_name = _('Issue')
        verbose_name_plural = _('Issues')
        get_latest_by = 'published_at'

    def get_absolute_url(self):
        return "/dergi/%s" % self.number

    def __unicode__(self):
        return self.subject

    def get_contents(self):
        return self.issue2content_set.prefetch_related(
            'content', 'content__authors', 'content__genres'
        ).filter(content__is_published=True)

    def save(self, *args, **kwargs):
        if self.is_published and not self.published_at:
            self.published_at = datetime.now()

        if not self.slug:
            self.slug = slugify(self.subject)[:99]
        self.updated_at = now()
        super(Issue, self).save(*args, **kwargs)

    def publish(self):
        self.is_published = True
        self.save()
        for content in self.contents.all():
            content.is_published = True
            for figure in content.figures.all():
                figure.is_published = True
                figure.save()
            content.save()
        destroy_cache()

    def unpublish(self):
        self.is_published = False
        self.save()
        for content in self.contents.all():
            content.is_published = False
            for figure in content.figures.all():
                figure.is_published = False
                figure.save()
            content.save()
        destroy_cache()

    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "subject__icontains",)


class Issue2Content(models.Model):
    issue = models.ForeignKey(Issue, verbose_name=_('Issue'))
    content = models.ForeignKey(
        IssueContent, related_name='link_to_issue',
        verbose_name=_('Content'))
    order = models.IntegerField(verbose_name=_('Order'), null=True, default=0)
    is_subject = models.BooleanField(verbose_name=_('Is Subject'), blank=True)

    def __unicode__(self):
        return '%s (%s %s) -> %s, order: %s' % (
            self.issue.subject, _('Number'), self.issue.number,
            self.content.title, self.order)

    class Meta:
        verbose_name = _('Content')
        verbose_name_plural = _('Contents')
        ordering = ['order']
        unique_together = ('issue', 'content', )


class IssueFile(models.Model):
    FORMATS = (('ePub3', 'ePub3'),
               ('PDF', 'PDF'))

    EXTENSIONS = {'ePub3': 'epub',
                  'PDF': 'pdf'}

    issue = models.ForeignKey(Issue, verbose_name=_('Issue'))
    issue_file = models.FileField(
        upload_to="files/issue/", verbose_name=_('File'))
    format = models.CharField(
        max_length=16, verbose_name=_('Format'),
        choices=FORMATS, default="ePub3")

    def __unicode__(self):
        return "%(issue)s -> %(format)s" % {'issue': self.issue.slug,
                                            'format': self.format}

    def get_filename(self):
        return "cerci-sayi-%(number)s.%(format)s" % {
            'number': self.issue.number,
            'format': self.EXTENSIONS[self.format]}

    class Meta:
        verbose_name = _('File')
        verbose_name_plural = _('Files')

templates/author.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load thumbnail %}
{% load author %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "css/author.css" %}" type="text/css"/>
  <link rel="stylesheet" href="{% static "css/toc.css" %}" type="text/css"/>
{% endblock %}

{% block content %}
<section class="author">
    <h1>{{ author.name }}
    {% if user.is_staff %}
        <a href="{% url 'admin:cerci_content_author_change' author.id %}"><i class="fa fa-edit"></i></a>
    {% endif %}
    </h1>
    <section class="description">
        {% if author.image %}
          <img class="author-image pull-left col-md-4" src="{% thumbnail author.image 360x430 box=author.cropping crop detail bw %}" alt="{{ author.name }}" title="{{ author.name }}" />
        {% endif %}
        {% if author.biography %}
            {{ author.biography|urlizetrunc:15 }}
        {% else %}
            <div class="clearfix"></div>
        {% endif %}
    </section>
</section>
<div class="clearfix"></div>
{% if hascontent %}
  {% include "partials/author_tabs.html" with active=active %}
  <div class="clearfix"></div>
  {% if active == 0 %}
  <section class="table-of-contents">
    {% for content in author.contents %}
        {% with content.issue_set.all.0 as issue %}
        {% if content.is_published %}
          <section class="issuecontent {% if issue2content.is_subject %}is-subject{% endif %}">
              {% include "partials/toc_bg.html" %}
              <div class="issuecontent-link">
                <h1>
                  <a href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}">{{ content.title }}</a>
                </h1>
                <h2>{{ content.authors.all|author_list|safe }}</h2>
                {% if content.spot %}
                {{ content.spot|truncatewords_html:100|striptags|safe }}
                {% else %}
                {{ content.body|truncatewords_html:100|striptags|safe }}
                {% endif %}
                <a class="more" href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}" data-toggle="tooltip" data-placement="top" title="Devamını oku" data-container="body" ><img src="{% static "images/more.png" %}" /></a>
                {% if issue2content.is_subject %}
                <img class="subject" src="{% static "images/subject.png" %}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Günebakan" />
                {% endif %}
              </div>
          </section>
        {% endif %}
        {% endwith %}
    {% endfor %}
  </section>
  {% endif %}
  {% if active == 1 %}
  <section class="table-of-contents">
    {% for content in author.figures %}
        {% with content.issue_set.all.0 as issue %}
        {% if content.is_published %}
          <section class="issuecontent {% if issue2content.is_subject %}is-subject{% endif %}">
              {% include "partials/toc_bg.html" %}
              <div class="issuecontent-link">
                <h1>
                  <a href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}">{{ content.title }}</a>
                </h1>
                <h2>{{ content.authors.all|author_list|safe }}</h2>
                {% if content.spot %}
                {{ content.spot|truncatewords_html:100|striptags|safe }}
                {% else %}
                {{ content.body|truncatewords_html:100|striptags|safe }}
                {% endif %}
                <a class="more" href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}" data-toggle="tooltip" data-placement="top" title="Devamını oku" data-container="body" ><img src="{% static "images/more.png" %}" /></a>
                {% if issue2content.is_subject %}
                <img class="subject" src="{% static "images/subject.png" %}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Günebakan" />
                {% endif %}
              </div>
          </section>
        {% endif %}
        {% endwith %}
    {% endfor %}
  </section>
  {% endif %}

  {% if active == 2 %}
  <section class="table-of-contents">
    {% for content in author.figure_contents %}
        {% with content.issue_set.all.0 as issue %}
        {% if content.is_published %}
          <section class="issuecontent {% if issue2content.is_subject %}is-subject{% endif %}">
              {% include "partials/toc_bg.html" %}
              <div class="issuecontent-link">
                <h1>
                  <a href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}">{{ content.title }}</a>
                </h1>
                <h2>{{ content.authors.all|author_list|safe }}</h2>
                {% if content.spot %}
                {{ content.spot|truncatewords_html:100|striptags|safe }}
                {% else %}
                {{ content.body|truncatewords_html:100|striptags|safe }}
                {% endif %}
                <a class="more" href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}" data-toggle="tooltip" data-placement="top" title="Devamını oku" data-container="body" ><img src="{% static "images/more.png" %}" /></a>
                {% if issue2content.is_subject %}
                <img class="subject" src="{% static "images/subject.png" %}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Günebakan" />
                {% endif %}
              </div>
          </section>
        {% endif %}
        {% endwith %}
    {% endfor %}
  </section>
  {% endif %}


  {% if active == 3 %}
  <div class="row covers">
    {% for issue in author.covers %}
      <section class="issue col-md-4">
        <a href="{% url 'current_issue' issue_number=issue.number %}">
          <img class="cover" src="{{ issue.cover|thumbnail_url:'cover' }}" alt="{{ issue.subject }}" title="{{ issue.subject }}" />
        </a>
      </section>
    {% endfor %}
  </div>
  {% endif %}
{% endif %}
{% endblock %}

templates/authors.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load thumbnail %}
{% load author %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "css/authors.css" %}" type="text/css"/>
{% endblock %}

{% block content %}
<section class="contents genre">
  <h1 class="page-header">ÇERÇİLER</h1>
  <ul class="list-inline">
  {% for initial in initials %}
  <li>
  <h2><a href="{% url 'author_list' initial=initial %}">{{ initial }}</a></h2>
  </li>
  {% endfor %}
  </ul>
  <h1 class="page-header">{{ initial }}</h1>
    <ul class="list-unstyled">
      {% for author in authors %}
      <li>
        <div class="author image-wrapper pull-left">
          <a href="{% url 'author' author_slug=author.slug %}">
            <img class="cover" src="{% thumbnail author.image 50x50 box=author.cropping crop detail bw %}" title="{{ author.name }}" alt="" />
          </a>
        </div>
        <h3>
          <a class="pull-left" href="{% url 'author' author_slug=author.slug %}">{{ author.name }}</a>
        </h3>
        <div class="clearfix"></div>
      </li>
      <hr/>
      {% endfor %}
    </ul>
</section>
{% endblock %}

templates/base.html
{% load static from staticfiles %}{% load bootstrap %}{% load turkish %}<!DOCTYPE html>
<html lang="tr-TR" xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://ogp.me/ns/fb#">
  <head>
    <title>{% block head_title %}Çerçi{% endblock %}</title>
    {% block head %}
    {% include "head.html" %}
    {% endblock %}
  </head>
  <body>
    {% block body %}
      <header class="clearfix">
        {% block logo %}
        {% endblock %}
        {% block navigation %}
        <nav role="navigation" class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" data-target="#navbarCollapse"
                data-toggle="collapse" class="navbar-toggle">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">
              <img class="rotate" src="{% static 'images/cerci_logo2_white.png' %}" style="height:30px" />
              </a>
            </div>

            <div id="navbarCollapse" class="collapse navbar-collapse">
              <ul class="auto-active nav navbar-nav navbar-left"> 
                <li><a href="{% url 'manifest' %}">MANİFESTO</a></li>
                <li><a href="{% url 'crew' %}">EKİP</a></li>  
                <li><a href="{% url 'author_list' %}">ÇERÇİLER</a></li>
                <li><a href="{% url 'sendus' %}">YAZI GÖNDER</a></li>  
                <li><a href="{% url 'blog' %}">BLOG</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle"
                      title="Abone ol"
                      data-toggle="dropdown" role="button"
                      aria-expanded="false"><i class="fa fa-book"></i>
                  </a>
                  <div class="dropdown-menu" role="menu">
                    <div class="subscription-form">
                      <h3>E-posta aboneliği</h3>
                      <form action="{% url 'subscribe_form' %}" method="post" class="ajax-form subscribe-form">
                      <p>
                        Abone olun ve yeni sayımız çıktığı anda haberiniz olsun.<br/>
                        (Abonelikten istediğiniz zaman ayrılabilirsiniz.)
                      </p>
                      {% csrf_token %}
                      {{ subscribe_form|bootstrap:'forceplaceholder' }}
                      <button type="submit" class="btn">Abone ol</button>
                      </form>
                      <div class="clearfix"></div>
                      <div class="subscribe-success">
                        E-posta aboneliğine üyeliğiniz başarıyla gerçekleşti.<br/>
                        Bir kayıt daha yapmak için <a href="{% url 'subscribe_form' %}" class="another-subscription">tıklayın</a>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle"
                      data-toggle="dropdown" role="button"
                      aria-expanded="false"><i class="fa fa-search"></i>
                  </a>
                  <div class="dropdown-menu" role="menu">
                    <form action="/arama" class="navbar-form" role="search">
                      <div class="form-group">
                        <input type="text" class="form-control" name="q" placeholder="Arama" />
                      </div>
                    </form>
                  </div>
                </li>
              </ul>
              {% block social %}
              <ul class="nav navbar-nav navbar-right social">
                <li>
                  <a href="https://www.facebook.com/CerciSanat" target="_blank"
                    title="Facebook'ta Çerçi Sanat">
                      <i class="fa fa-facebook"></i>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/cercisanat" target="_blank"
                    title="Twitter'da Çerçi Sanat">
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
                <li>
                  <a href="https://plus.google.com/107839000424667573646/posts"
                    target="_blank" title="Google+'ta Çerçi Sanat">
                    <i class="fa fa-google-plus"></i>
                  </a>
                </li>
                <li>
                  <a href="http://pinterest.com/cercisanat/" target="_blank"
                    title="Pinterest'te Çerçi Sanat">
                    <i class="fa fa-pinterest-p"></i>
                  </a>
                </li>
                <li>
                  <a href="https://instagram.com/cercisanat/" target="_blank"
                    title="Instagram'da Çerçi Sanat">
                    <i class="fa fa-instagram"></i>
                  </a>
                </li>
                <li>
                  <a href="https://github.com/cercisanat" target="_blank"
                    title="Github'da Çerçi Sanat">
                    <i class="fa fa-github"></i>
                  </a>
                </li>

              </ul>
              {% endblock %}
            </div>
          </div>
        </nav> 
        {% endblock %}
        <div class="clearfix"></div>
      </header>
    <div class="container">
      {% for message in messages %}
        <div class="alert alert-{% if message.tags %} {{ message.tags }}{% endif %}">
          <button type="button" class="close" data-dismiss="alert">×</button>
          {{ message|safe }}
        </div>
      {% endfor %}
      {% block genres %}
      <div class="unnecessary-zone">
        <div class="row row-centered logo-wrapper">
          <div class="col-centered">
            <a href="/" class="logo">
              <img class="add-rotate-slow" src="{% static 'images/cerci_wheel_black2.png' %}" />
              <img src="{% static 'images/cerci_black2.png' %}" />
            </a>
          </div>
        </div>
        {% comment %}
        <div class="row row-centered genres-wrapper">
          <div class="col-centered">
            <ul class="auto-active list-inline genres">
            {% for genre in genres %}
            {% if forloop.counter0 %}
            <li class="separator">/</li>
            {% endif %}
            <li>
              <a class="genre" data-toggle="tooltip" data-placement="bottom"
                title="{{ genre.description|safe }}" data-html="true"
                href="{% url 'genre' genreslug=genre.slug %}">
                {{ genre.name|turkish_upper }}
              </a>
            </li> 
            {% endfor %}
            </ul>
          </div>
        </div>
        {% endcomment %}
      </div>
      {% endblock %}

      {% block content %}
      {% endblock %}
      <div class="clearfix"></div>
      <footer class="clearfix">
        {% block footer_navigation %}
        <ul class="primary-menu pull-left">
          {% include 'navigation.html' %}
        </ul>
        {% endblock %}
        <div class="copyright pull-right">
          <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="{% static "images/cc.png" %}" /></a>
        </div>
      </footer>
    </div>
    {% endblock %}
  </body>
</html>

templates/category.html
{% extends "base.html" %}
{% load thumbnail %}
{% load author %}
{% load static from staticfiles %}

{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static "css/genre.css" %}" type="text/css"/>
<link rel="stylesheet" href="{% static "css/toc.css" %}" type="text/css"/>
{% endblock %}


{% block content %}
<section class="table-of-contents">
  {% for content in contents %}
      {% with content.issue_set.all.0 as issue %}
      {% if content.is_published %}
        <section class="issuecontent {% if issue2content.is_subject %}is-subject{% endif %}">
            {% include "partials/toc_bg.html" %}
            
            <div class="issuecontent-link">
              <h1>
                <a href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}">{{ content.title }}</a>
              </h1>
              <h2>{{ content.authors.all|author_list|safe }}</h2>
              {% if content.spot %}
              {{ content.spot|truncatewords_html:100|striptags|safe }}
              {% else %}
              {{ content.body|truncatewords_html:100|striptags|safe }}
              {% endif %}
              {% include "partials/tags.html" %}
              <a class="more" href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}" data-toggle="tooltip" data-placement="top" title="Devamını oku" data-container="body" ><img src="{% static "images/more.png" %}" /></a>
              {% if issue2content.is_subject %}
              <img class="subject" src="{% static "images/subject.png" %}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Günebakan" />
              {% endif %}
            </div>
        </section>
      {% endif %}
      {% endwith %}
  {% endfor %}
</section>
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block content %}
<section class="sendus content">
    <h1>İletişim</h1>
    Biz ulaşmak için: <a href="mailto:iletisim@cercisanat.com">iletisim@cercisanat.com</a>
</section>
{% endblock %}

templates/issue.html
{% extends "base.html" %}
{% load thumbnail %}
{% load author %}
{% load static from staticfiles %}
{% load compress %}
{% block head_title %}
{{ block.super }}
-Sayı {{ issue.number }}
{% endblock %}

{% block head %}
  {{ block.super }}
  {% compress css %}
  <link rel="stylesheet" href="{% static "css/issuecontent.css" %}" type="text/css"/>
  <link rel="stylesheet" href="{% static "css/issue.css" %}" type="text/css"/>
  <link rel="stylesheet" href="{% static "css/toc.css" %}" type="text/css"/>
  {% endcompress %}
  {% compress js %}
  <script type="text/javascript" src="{% static "js/jquery.expander.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/jquery.ellipsis.min.js" %}"></script>
  <script type="text/javascript">
  var static_url = "{% static "" %}";
  </script>
  <script type="text/javascript" src="{% static "js/responsive/issue.js" %}"></script>
  <script type="text/javascript" src="{% static "js/responsive/issuecontent.js" %}"></script>
  {% endcompress %}
{% endblock %}

{% block genres %}
{% endblock %}

{% block body %}
<div class="container">
<section class="issue contents clearfix">
    {% include "partials/toc_container.html" %}

    <section class="frontmatter row">
        <div class="image-files-wrapper pull-left col-md-5">
          {% if issue.cover_video %}
          <video width="380" height="500" autoplay loop poster="{{ issue.cover|thumbnail_url:'cover' }}">
            <source src="{{ issue.cover_video.url }}" type="video/mp4" />
          </video>
          {% else %}
          <a class="galleryitem" href="{{ issue.cover.url }}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Daha büyük boyutlusunu görmek ve yakınlaştırabilmek için tıklayın.">
          <img class="cover" src="{{ issue.cover|thumbnail_url:'cover' }}" alt="Çerçi Sayı {{ issue.number }}, {{ issue.published_at|date:"F Y" }}" />
          </a>
          {% endif %}
        </div>
        <div class="issue-info col-md-7">
          <hgroup>
              <h1 class="number">Sayı {{ issue.number }}, {{ issue.published_at|date:"F Y" }}
              {% if user.is_staff %}
              <a href="{% url 'admin:cerci_issue_issue_change' issue.id %}"><i class="fa fa-edit"></i></a>
              {% endif %}
              </h1>
          </hgroup>
          <ul class="nav nav-pills">
            {% if issue.editorial %}
            <li><a href="#editorial">EDİTÖRDEN</a></li>
            {% endif %}
            <li><a href="#table-of-contents">İÇİNDEKİLER</a></li>
          </ul>
          
          <section class="copyright_page">
            <strong>Yazar ve Çizerlerimiz:</strong><br/>{{ issue.copyright_page|safe|removetags:"script style" }}<br/>
            {% if issue.cover_design %}<strong>Kapak Tasarımı:</strong> {{ issue.cover_design.all|author_list|safe }}{% endif %}
          </section>

          {% if issue.issuefile_set.all.count %}
          <div class="files">
              {% for file in issue.issuefile_set.all %}
              <a class="file" href="{{ file.issue_file.url }}" download="{{ file.get_filename }}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="Bu dergiyi {{ file.format }} formatında indirebilrisiniz.">{{ file.format }}</a>
              {% endfor %}
          </div>
          {% endif %}
        </div>
    </section>
    
    {% if issue.editorial %}
    <h1 id="editorial" class="page-header">EDİTÖRDEN</h1>
    <section class="editorial">
      <h2>{{ issue.editorial_title }}</h2>
      {{ issue.editorial|safe|removetags:"script style" }}
    </section>
    {% endif %}

    <h1 id="table-of-contents" class="page-header">İÇİNDEKİLER</h1>
    <section class="table-of-contents">
        {% for issue2content in issue.issue2content_set.all %}
            {% with issue2content.content as content %}
            {% if content.is_published or request.user.is_staff %}
            <div class="issuecontet-wrapper">
              {% if issue2content.is_subject %}
                <div class="is-subject">
                GÜNEBAKAN
                </div>
              {% endif %}

              <section class="issuecontent"> 
                  {% include "partials/toc_bg.html" %} 
                  <div class="issuecontent-link">
                    <h1>
                      <a href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}">{{ content.title }}</a>
                    </h1>
                    <h2>{{ content.authors.all|author_list|safe }}</h2>
                    {% if content.spot %}
                    {{ content.spot|truncatewords_html:100|striptags|safe }}
                    {% else %}
                    {{ content.body|truncatewords_html:100|striptags|safe }}
                    {% endif %}
                    <a class="more" href="{% url 'current_issuecontent' issue_number=issue.number contentslug=content.slug %}"
                      data-toggle="tooltip" data-placement="top" title="Devamını oku" data-container="body">
                      <i class="fa fa-chevron-circle-right fa-lg"></i>
                    </a>
                  </div>
              </section>
            </div>
            {% endif %}
            {% endwith %}
        {% endfor %}
    </section>
</section>
</div>
{% endblock %}

templates/navigation.html
{% load static from staticfiles %}
<!-- <li><a href="{% url 'author_list' %}">Yazarlar</a></li>-->
<li><a href="http://cercisanat.blogspot.com.tr/">BLOG</a></li>
<li><a href="{% url 'manifest' %}">MANİFESTO</a></li>
<li><a href="{% url 'crew' %}">EKİP</a></li>
<li><a href="{% url 'rules' %}">SİTE KURALLARI</a></li>
<li><a href="{% url 'sendus' %}">YAZI GÖNDER</a></li>
<li><a href="{% url 'contact' %}">İLETİŞİM</a></li>

templates/nocontent.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block content %}
  <h1>Henüz içerik girilmemiş.</h1>
{% endblock %}